language: node_js
node_js:
- '0.12'
env:
  global:
  - secure: "VzRKt661c1hg3xUBMNOl39ERNAeYmfrGq3wSnUhBiA7F8mZX2ts1oFmK189nZAqxi6oWT7P+mg76PPHN9dKdSinsBdaGFuo1lc2MubI7vk9/C+yiHU/GRF60RCGuLBoUQpFgs9nK+zvQhFw9Nm9R7ZICbeIRU3tK4fMJMhciyFzhdJ74yACv7mY7leuVVdggZGSUVqOGmoxFdp38BPCiQOVOacJTU9o9dAp5ph3NUM4CxjZInQKAEbA3pmezf8rjKSFPa1TWHLGdZ746m0BgVPaYnpyfgwftn43kh1BnKEGfO9p6H6WAJqYjrDnY4RbYLFQG4e2gel1otOTapOz9LUJJgigc+aLEzDlbypwwt+1k38b0tnls9yyAYJEb2xOvbSDibpWjl9d17j8wWhU/S/olmqO3ZYMtagwUU0q/2Wxh3dFSnSKnxoDnIhkH+7chkUBA5OX9HAWq9KRaeCUSI2TxjomHmQkUOXKDfZlAE6waj0G+PgVYxVnYjrFopOt236DYgCI55Ek4Z/ra2t0aOMBvkK9ytiepmGRbR/satsHurURFST5XJy/VZ8389D9xvHLWoyY7xFwFhzv0/n7ksWUuwq9gozNhT3yJ5g5D7pLZHkh0O6j2BLs5NQiWdSRQb2LY6r/UMN5Bqgi8kZzFZ24jFsP+XBlYV68ty6lgMKU="
  - secure: "cEo5DpMTakkxqIDI2TP18T7qpPb/cy/It1Iw1/onu9Ekq7czFvjegLwQ1xfnVcuHuTM/N9C5GKC3OO1b7xH/fiYn7aTssyhhEdyCE7fY8F40+1k3W7arPXFnh+pJT0UZG3y+Ovg610tdsPNkLCAZiUrNw2kV8H88F2AUjDh+SQyfBNM1VwvZBrT0JK1R+FeLLimxeFnZJL6hth+ukvzVcgw0QHxkPQ9oOviggElmeTXhGvYgmBJqjdVU1NkZfCKvBwRiUNXir3+3eyBJd5hbeVoJZ54yCZMLNJBX4W+HmKzZlf0Hfl6liJr9ymy39iyKPnI+80vizfG1brKKBzkGBKRBvxmxW6cc6uZQBGVPnDe2i55tc8nqCsbXkzZHx6flvTH0lNCmH5JUxgx7QL92EFkT+5GcVhxRCVjcITXdxxYQWAgLezdofSFzmy7OQiDqNs/l4E2E5VYHhb36W0KVYiJT1OA2udQBkWVzKomfxO9zA9GWQwVbdWuvKiXqI0ibTNGe1w11E4VZ/SJbUAG3tLkYtMNrwiH8CK/EybnO4ugWT417uKm/sMautq54aKOIlspDm2cdZ1Z8KoR0WORUzXQ983Obm4a/kF3R1FhKeOn+Zq8Vithvi9nRbbI8U2ZKXIEMSbY+VUJT2mD3LFErVSO6YYZzqxQth54uMKrpspY="
branches:
  only:
  - develop
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: contact@makemepulse.com
  api_key:
    secure: JOHeYV1ylqO3Go068lHsvBX+Vh687t/MJ4i9C6Lta77ZubtsK+YywR10C3RSR1UvWKtwrx+d33QBaBhk1sDjjL0YJ3DdKr4j/V2DM+ZRw5zut2V4YWlFhamutLpxntERhA6FrXPgtBGTaKwyGKk72tcGolW86T8MU3bLJhmO5Dmrl8a9N1eiu1BWxVEGTLKX3oedm0E8ozGhoezeSGedg6ByL3XOdJ8tzAoTgxnFs0Jd3dQIEdrj27uHiCEdhnejWX/kNzGLifsQMf/SpbGeIhzCE40i27ZdhBAWtDp+YUGCh9Hwpj5OqMcdEZJ6e0Gy91FzDKQdqmDSvEVRUISuwUyHr04WRZSHVROSEHrSxsbdID6Ay3rNEUYAtotIK9CxYBTqZOs4arvMTdE91fXl4XQikPT6/r88mFdNToyel68+PO/a1j3p/AKRB5NKmwQ37WRYSws0enc9CN6KACBouw5Y4irv+yP0NCVph1m+qNJFz++ISEfmAhZROi13v+A6FSEgSuxsf4ATMXwL04FX48Mvp26vLU1HR4EKOyXbU5Wg2oR/EbaJdiOoxNkgL9KkWlN9Q2uqqKkCiryImTravd7uZ0Eh/IIBvzp/iU80F1ERVXkHgLwgDa+ZgVVa0d7z/EBQXHt9j4dfUpCflpJa41CmOqtJeZm7EKR2O3aFiHw=
  on:
    branch: master
    repo: plepers/nanogl-depth-texture
